## version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db_data/init-db:/docker-entrypoint-initdb.d
      - ./db_data/mysql-data:/var/lib/mysql
    ports:
      - "3306:${MYSQL_PORT}"

  currency:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    environment:
      NODE_ENV: DOCKER
      MYSQL_HOST: mysql-db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_ROOT_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

volumes:
  mysql-data:
